image:
  file: .gitpod.Dockerfile

tasks:
  - command: envsubst < src/environments/environment_template.ts > src/environments/environment.ts
  - command: envsubst < src/environments/environment.prod_template.ts > src/environments/environment.prod.ts
  - command: npm i

ports:
  - port: 8100

vscode:
  extensions:
    - ms-vscode.vscode-typescript-tslint-plugin@1.2.2:0nQ3PEEA0NPEt3UcbCYiIQ==
    - johnpapa.Angular2@9.1.2:uM4PeIXJe98IILNHmOn+nA==
    - christian-kohler.npm-intellisense@1.2.1:vghMIRDy8/ygZPJWq/9oEQ==
    - eg2.vscode-npm-script@0.3.11:Np1+d2YoqckGfeIuPylSEw==
